### ISSUE TITLE
deno-puppeteer or deno-puppeteer-core ?

### ISSUE THREAD

**Issue by mamereu** [lucacasonato/deno-puppeteer#9]
Great job !!!
I think there is some more good news about installation and browser requirements.

The README says '_Puppeteer can use any recent version of Chromium or Firefox Nightly, but this version of Puppeteer is only validated against a specific version_'[chromium 88.0.4298.0].  
In my opinion saying "this version of Puppeteer" is misleading because what we have here is the deno version of puppeteer-core not of puppeteer.
Puppeteer source has two major subtrees, common and node, and while both are needed for the _puppeteer product_ only the first one is used by the _library_ puppeteer-core. As pointed out in [puppeteer vs puppeteer-core](https://github.com/puppeteer/puppeteer/blob/main/docs/api.md#puppeteer-vs-puppeteer-core). installing the puppeteer product means downloading the browser, but for puppeteer-core only an explicit `executablePath` option has to be set in `puppeteer.connect` or `puppeteer.launch` .
I have been able to import deno-puppeteer with no browser dowloading in the following conditions:
- linux fedora 33, google-chrome-stable 87.0.4280.88 and chromium-browser 87.0.4280.88
- windows 10, chrome 84.0.4147.135

On both systems, however, pointing the executablePath to firefox starts the browser but eventually exits with an error.

**Comment by lucacasonato** [comment]
Hi @mamereu. Thanks for your feedback.

This is actually a port of `puppeteer`, not juust `puppeteer-core`. `deno-puppeteer` respects the `PUPPETEER_*` env vars, and by default you do not have to pass the `executablePath` option because deno-puppeteer has a vendored version of Chromium. `puppeteer-core` can be found at `//vendor/puppeteer-core/puppeteer/common` (yes, unfortunate naming of the vendor dir), while the `node` subtree equivalent `deno` can be found at `//vendor/puppeteer-core/puppeteer/deno`. This folder structure still requires some major cleanup (ie why is the custom deno source code in the `vendor` dir?).

Because Deno modules do not have a installation step (no post-install npm hook), but we somehow have to install the vendored Chromium, I came up with two solutions:
1. Have the user run a separate `installer` script before the first run that installs the vendored Chromium (or firefox nightly for that matter)
2. Automatically install the vendored version of Chromium on the first call to `puppeteer.launch` if no `executablePath` is specified

Currently we are using solution 1, but it would be trivial to implement solution 2 if there is need.

**Comment by mamereu** [comment]
Ok @lucacasonato, my point is that there already is a **solution 3.** that allows running your module with no more than the import statement and the `executablePath` option. 
 If you say that my tests are not enough to certify solution 3, I can only agree with you. 
However,I had a few scripts based on the npm puppeteer-core package that now can happily run in deno just by replacing the import statement (and other minor adjustments). 
So, thanks again for the deno-puppeteer module !!!

**Comment by lucacasonato** [comment]
Yup that is also possible. I am going to close this, because I don't think there is anything actionable here. If you think there is something actionable to do, please open another issue :-)
